// VENDORED from JakobMelchard/.config tokens/tokens.swift @v1.2.0. Do not edit; run config-sync.
// Code generated by tokens/build_tokens.py from tokens/tokens.json (JakobMelchard v1). DO NOT EDIT.

import SwiftUI

/// Dark-theme colour tokens and px radii, one per token in tokens.json. `Theme` exposes them.
enum GeneratedTokens {
  static let bg = Color(hex: 0x0B0D10)
  static let card = Color(hex: 0x15171F)
  static let glass = Color(hex: 0xFFFFFF).opacity(0.06)
  static let line = Color(hex: 0x6272A4).opacity(0.25)
  static let grid = Color(hex: 0xEEF4FF).opacity(0.035)
  static let fg = Color(hex: 0xF8F8F2)
  static let muted = Color(hex: 0x6272A4)
  static let accent = Color(hex: 0x8BE9FD)
  static let pink = Color(hex: 0xFF79C6)
  static let purple = Color(hex: 0xBD93F9)
  static let green = Color(hex: 0x50FA7B)
  static let orange = Color(hex: 0xFFB86C)
  static let red = Color(hex: 0xFF5555)
  static let hover = Color(hex: 0x8BE9FD).opacity(0.07)
  static let ghost = Color(hex: 0xFFFFFF).opacity(0.18)
  static let scrim = Color(hex: 0x000000).opacity(0.7)
  static let scrimBlur = Color(hex: 0x0B0D10).opacity(0.8)
  static let link = accent
  static let caret = red
  static let success = green
  static let warn = orange
  static let danger = red
  static let info = purple
  static let highlight = pink

  static let radiusXs: CGFloat = 2
  static let radiusSm: CGFloat = 3
  static let radiusMd: CGFloat = 8
  static let radiusLg: CGFloat = 10
  static let radiusXl: CGFloat = 14
  static let radius2xl: CGFloat = 28
  static let radiusPill: CGFloat = 999
}
